### ISSUE TITLE
[Source Request] https://readcomiconline.li/

### ISSUE THREAD

**Issue by aclup3** [Paperback-iOS/extensions-sources#50]
Could you plz add https://readcomiconline.li/ ? its easily the best comics source available. I know theres comecectra available, but that has fewer comics and is badly organized

**Comment by TheNetsky** [comment]
You can find it here: https://thenetsky.github.io/netskys-extensions/0.6/

**Comment by aclup3** [comment]
amazing! thank you so much. this is the best pack arround
