### ISSUE TITLE
[Source Request] Colored manga

### ISSUE THREAD

**Issue by jman501** [Paperback-iOS/extensions-sources#56]
https://coloredmanga.com/ 

For the color manga pages

**Comment by TheNetsky** [comment]
Already added https://github.com/Paperback-iOS/extensions-generic/

**Comment by jman501** [comment]
I'm talking about adding the colored manga website not completed manga. 

https://coloredmanga.com/

**Comment by TheNetsky** [comment]
Seems like you haven't actually looked...
https://paperback-ios.github.io/extensions-generic/madara/
